//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap { Locale(identifier: $0) } ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)

  /// Find first language and bundle for which the table exists
  fileprivate static func localeBundle(tableName: String, preferredLanguages: [String]) -> (Foundation.Locale, Foundation.Bundle)? {
    // Filter preferredLanguages to localizations, use first locale
    var languages = preferredLanguages
      .map { Locale(identifier: $0) }
      .prefix(1)
      .flatMap { locale -> [String] in
        if hostingBundle.localizations.contains(locale.identifier) {
          if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
            return [locale.identifier, language]
          } else {
            return [locale.identifier]
          }
        } else if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
          return [language]
        } else {
          return []
        }
      }

    // If there's no languages, use development language as backstop
    if languages.isEmpty {
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages = [developmentLocalization]
      }
    } else {
      // Insert Base as second item (between locale identifier and languageCode)
      languages.insert("Base", at: 1)

      // Add development language as backstop
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages.append(developmentLocalization)
      }
    }

    // Find first language for which table exists
    // Note: key might not exist in chosen language (in that case, key will be shown)
    for language in languages {
      if let lproj = hostingBundle.url(forResource: language, withExtension: "lproj"),
         let lbundle = Bundle(url: lproj)
      {
        let strings = lbundle.url(forResource: tableName, withExtension: "strings")
        let stringsdict = lbundle.url(forResource: tableName, withExtension: "stringsdict")

        if strings != nil || stringsdict != nil {
          return (Locale(identifier: language), lbundle)
        }
      }
    }

    // If table is available in main bundle, don't look for localized resources
    let strings = hostingBundle.url(forResource: tableName, withExtension: "strings", subdirectory: nil, localization: nil)
    let stringsdict = hostingBundle.url(forResource: tableName, withExtension: "stringsdict", subdirectory: nil, localization: nil)

    if strings != nil || stringsdict != nil {
      return (applicationLocale, hostingBundle)
    }

    // If table is not found for requested languages, key will be shown
    return nil
  }

  /// Load string from Info.plist file
  fileprivate static func infoPlistString(path: [String], key: String) -> String? {
    var dict = hostingBundle.infoDictionary
    for step in path {
      guard let obj = dict?[step] as? [String: Any] else { return nil }
      dict = obj
    }
    return dict?[key] as? String
  }

  static func validate() throws {
    try intern.validate()
  }

  /// This `R.color` struct is generated, and contains static references to 11 colors.
  struct color {
    /// Color `addMetricTint`.
    static let addMetricTint = Rswift.ColorResource(bundle: R.hostingBundle, name: "addMetricTint")
    /// Color `baseText`.
    static let baseText = Rswift.ColorResource(bundle: R.hostingBundle, name: "baseText")
    /// Color `galleryItemBackground`.
    static let galleryItemBackground = Rswift.ColorResource(bundle: R.hostingBundle, name: "galleryItemBackground")
    /// Color `metricBad`.
    static let metricBad = Rswift.ColorResource(bundle: R.hostingBundle, name: "metricBad")
    /// Color `metricDefault`.
    static let metricDefault = Rswift.ColorResource(bundle: R.hostingBundle, name: "metricDefault")
    /// Color `metricGood`.
    static let metricGood = Rswift.ColorResource(bundle: R.hostingBundle, name: "metricGood")
    /// Color `metricParamBackground`.
    static let metricParamBackground = Rswift.ColorResource(bundle: R.hostingBundle, name: "metricParamBackground")
    /// Color `metricStrockColor`.
    static let metricStrockColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "metricStrockColor")
    /// Color `metricText`.
    static let metricText = Rswift.ColorResource(bundle: R.hostingBundle, name: "metricText")
    /// Color `red`.
    static let red = Rswift.ColorResource(bundle: R.hostingBundle, name: "red")
    /// Color `secondaryText`.
    static let secondaryText = Rswift.ColorResource(bundle: R.hostingBundle, name: "secondaryText")

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "addMetricTint", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func addMetricTint(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.addMetricTint, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "baseText", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func baseText(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.baseText, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "galleryItemBackground", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func galleryItemBackground(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.galleryItemBackground, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "metricBad", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func metricBad(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.metricBad, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "metricDefault", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func metricDefault(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.metricDefault, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "metricGood", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func metricGood(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.metricGood, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "metricParamBackground", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func metricParamBackground(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.metricParamBackground, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "metricStrockColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func metricStrockColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.metricStrockColor, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "metricText", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func metricText(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.metricText, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "red", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func red(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.red, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "secondaryText", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func secondaryText(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.secondaryText, compatibleWith: traitCollection)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "addMetricTint", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func addMetricTint(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.addMetricTint.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "baseText", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func baseText(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.baseText.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "galleryItemBackground", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func galleryItemBackground(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.galleryItemBackground.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "metricBad", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func metricBad(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.metricBad.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "metricDefault", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func metricDefault(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.metricDefault.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "metricGood", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func metricGood(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.metricGood.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "metricParamBackground", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func metricParamBackground(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.metricParamBackground.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "metricStrockColor", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func metricStrockColor(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.metricStrockColor.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "metricText", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func metricText(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.metricText.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "red", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func red(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.red.name)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "secondaryText", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func secondaryText(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.secondaryText.name)
    }
    #endif

    fileprivate init() {}
  }

  /// This `R.entitlements` struct is generated, and contains static references to 1 properties.
  struct entitlements {
    struct comAppleSecurityApplicationGroups {
      static let groupAnymetricsApp = infoPlistString(path: ["com.apple.security.application-groups"], key: "group.anymetrics.app") ?? "group.anymetrics.app"

      fileprivate init() {}
    }

    fileprivate init() {}
  }

  /// This `R.file` struct is generated, and contains static references to 1 files.
  struct file {
    /// Resource file `GoogleService-Info.plist`.
    static let googleServiceInfoPlist = Rswift.FileResource(bundle: R.hostingBundle, name: "GoogleService-Info", pathExtension: "plist")

    /// `bundle.url(forResource: "GoogleService-Info", withExtension: "plist")`
    static func googleServiceInfoPlist(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.googleServiceInfoPlist
      return fileResource.bundle.url(forResource: fileResource)
    }

    fileprivate init() {}
  }

  /// This `R.image` struct is generated, and contains static references to 4 images.
  struct image {
    /// Image `appIconInfo`.
    static let appIconInfo = Rswift.ImageResource(bundle: R.hostingBundle, name: "appIconInfo")
    /// Image `minus`.
    static let minus = Rswift.ImageResource(bundle: R.hostingBundle, name: "minus")
    /// Image `plus`.
    static let plus = Rswift.ImageResource(bundle: R.hostingBundle, name: "plus")
    /// Image `request`.
    static let request = Rswift.ImageResource(bundle: R.hostingBundle, name: "request")

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "appIconInfo", bundle: ..., traitCollection: ...)`
    static func appIconInfo(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.appIconInfo, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "minus", bundle: ..., traitCollection: ...)`
    static func minus(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.minus, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "plus", bundle: ..., traitCollection: ...)`
    static func plus(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.plus, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "request", bundle: ..., traitCollection: ...)`
    static func request(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.request, compatibleWith: traitCollection)
    }
    #endif

    fileprivate init() {}
  }

  /// This `R.info` struct is generated, and contains static references to 1 properties.
  struct info {
    struct nsUserActivityTypes {
      static let configurationIntent = infoPlistString(path: ["NSUserActivityTypes"], key: "ConfigurationIntent") ?? "ConfigurationIntent"

      fileprivate init() {}
    }

    fileprivate init() {}
  }

  /// This `R.string` struct is generated, and contains static references to 1 localization tables.
  struct string {
    /// This `R.string.localizable` struct is generated, and contains static references to 68 localization keys.
    struct localizable {
      /// en translation: About
      ///
      /// Locales: en, ru
      static let infoTitle = Rswift.StringResource(key: "info.title", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Add
      ///
      /// Locales: en, ru
      static let httpheadersAddButton = Rswift.StringResource(key: "httpheaders.add.button", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Add
      ///
      /// Locales: en, ru
      static let metricAdd = Rswift.StringResource(key: "metric.add", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Add Header
      ///
      /// Locales: en, ru
      static let addmetricButtonAddHttpHeader = Rswift.StringResource(key: "addmetric.button.add-http-header", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Add Header
      ///
      /// Locales: en, ru
      static let httpheadersAddTitle = Rswift.StringResource(key: "httpheaders.add.title", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Add Metric
      ///
      /// Locales: en, ru
      static let metricAddTitle = Rswift.StringResource(key: "metric.add.title", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Add metric
      ///
      /// Locales: en, ru
      static let addmetricButtonAdd = Rswift.StringResource(key: "addmetric.button.add", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: AnyMetrics
      ///
      /// Locales: en, ru
      static let appName = Rswift.StringResource(key: "appName", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: AnyMetrics is open source project. Developed to solve own problem and published on GitHub.  If want to add metric to gallery send PullRequest to gallery repository.
      ///
      /// Locales: en, ru
      static let infoMessage = Rswift.StringResource(key: "info.message", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Application code
      ///
      /// Locales: en, ru
      static let infoGithubAppRepo = Rswift.StringResource(key: "info.github-app-repo", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Bad
      ///
      /// Locales: en, ru
      static let metricValueBad = Rswift.StringResource(key: "metric.value.bad", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Bitcoin
      ///
      /// Locales: en, ru
      static let addmetricFieldTitlePlaceholder = Rswift.StringResource(key: "addmetric.field.title-placeholder", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Case sensitive
      ///
      /// Locales: en, ru
      static let addmetricFieldCaseSensitive = Rswift.StringResource(key: "addmetric.field.case-sensitive", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Check HTTP Status (20x is success)
      ///
      /// Locales: en, ru
      static let addmetricFieldTypeMetricCheckstatus = Rswift.StringResource(key: "addmetric.field.type-metric-checkstatus", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Close
      ///
      /// Locales: en, ru
      static let commonClose = Rswift.StringResource(key: "common.close", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Compare
      ///
      /// Locales: en, ru
      static let addmetricFieldRuleTypeEqual = Rswift.StringResource(key: "addmetric.field.rule-type-equal", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Configure
      ///
      /// Locales: en, ru
      static let addmetricFieldValueConfigure = Rswift.StringResource(key: "addmetric.field.value-configure", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Create custom metric
      ///
      /// Locales: en, ru
      static let metricAddCustom = Rswift.StringResource(key: "metric.add.custom", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Currency
      ///
      /// Locales: en, ru
      static let addmetricFieldValueTypeCurrency = Rswift.StringResource(key: "addmetric.field.value-type-currency", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Cut if longer
      ///
      /// Locales: en, ru
      static let addmetricFieldMaxLength = Rswift.StringResource(key: "addmetric.field.max-length", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Delete metric
      ///
      /// Locales: en, ru
      static let metricActionsConfirmDelete = Rswift.StringResource(key: "metric.actions.confirmDelete", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Edit
      ///
      /// Locales: en, ru
      static let addmetricTitleEdit = Rswift.StringResource(key: "addmetric.title-edit", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Edit
      ///
      /// Locales: en, ru
      static let metricActionsEdit = Rswift.StringResource(key: "metric.actions.edit", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Enter parse HTML rule, see FAQ
      ///
      /// Locales: en, ru
      static let addmetricFieldHtmlParseRulePlaceholder = Rswift.StringResource(key: "addmetric.field.html-parse-rule-placeholder", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Enter parse JSON rule, see FAQ
      ///
      /// Locales: en, ru
      static let addmetricFieldJsonParseRulePlaceholder = Rswift.StringResource(key: "addmetric.field.json-parse-rule-placeholder", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Enter value
      ///
      /// Locales: en, ru
      static let addmetricFieldRuleTypePlaceholder = Rswift.StringResource(key: "addmetric.field.rule-type-placeholder", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: FAQ
      ///
      /// Locales: en, ru
      static let commonFaq = Rswift.StringResource(key: "common.faq", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Format settings
      ///
      /// Locales: en, ru
      static let addmetricSectionFormatSettings = Rswift.StringResource(key: "addmetric.section.format-settings", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Gallery repository
      ///
      /// Locales: en, ru
      static let infoGithubGalleryRepo = Rswift.StringResource(key: "info.github-gallery-repo", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Good
      ///
      /// Locales: en, ru
      static let metricValueGood = Rswift.StringResource(key: "metric.value.good", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: HTTP Headers
      ///
      /// Locales: en, ru
      static let addmetricSectionHttpHeaders = Rswift.StringResource(key: "addmetric.section.http-headers", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: HTTP Method
      ///
      /// Locales: en, ru
      static let addmetricFieldHttpMethod = Rswift.StringResource(key: "addmetric.field.http-method", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: HTTP-header title
      ///
      /// Locales: en, ru
      static let httpheadersEnterName = Rswift.StringResource(key: "httpheaders.enter-name", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Header Value
      ///
      /// Locales: en, ru
      static let httpheadersEnterValue = Rswift.StringResource(key: "httpheaders.enter-value", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Make request
      ///
      /// Locales: en, ru
      static let addmetricButtonMakeRequest = Rswift.StringResource(key: "addmetric.button.make-request", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Measure
      ///
      /// Locales: en, ru
      static let addmetricFieldParamMeasure = Rswift.StringResource(key: "addmetric.field.param-measure", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Must contain
      ///
      /// Locales: en, ru
      static let addmetricFieldRuleTypeContains = Rswift.StringResource(key: "addmetric.field.rule-type-contains", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: New metric
      ///
      /// Locales: en, ru
      static let addmetricTitleNew = Rswift.StringResource(key: "addmetric.title-new", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: No
      ///
      /// Locales: en, ru
      static let addmetricFieldRuleTypeNone = Rswift.StringResource(key: "addmetric.field.rule-type-none", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: No response
      ///
      /// Locales: en, ru
      static let addmetricTextNoResponse = Rswift.StringResource(key: "addmetric.text.no-response", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Optional
      ///
      /// Locales: en, ru
      static let commonOptional = Rswift.StringResource(key: "common.optional", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Parse HTML
      ///
      /// Locales: en, ru
      static let addmetricFieldTypeMetricWeb = Rswift.StringResource(key: "addmetric.field.type-metric-web", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Parse JSON
      ///
      /// Locales: en, ru
      static let addmetricFieldTypeMetricJson = Rswift.StringResource(key: "addmetric.field.type-metric-json", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Press + and add your first metric
      ///
      /// Locales: en, ru
      static let metricPlaceholder = Rswift.StringResource(key: "metric.placeholder", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Price, USD
      ///
      /// Locales: en, ru
      static let addmetricFieldParamMeasurePlaceholder = Rswift.StringResource(key: "addmetric.field.param-measure-placeholder", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Rate application
      ///
      /// Locales: en, ru
      static let infoRate = Rswift.StringResource(key: "info.rate", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Raw
      ///
      /// Locales: en, ru
      static let addmetricFieldValueTypeNone = Rswift.StringResource(key: "addmetric.field.value-type-none", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Refresh
      ///
      /// Locales: en, ru
      static let metricActionsUpdateValue = Rswift.StringResource(key: "metric.actions.update-value", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Remove
      ///
      /// Locales: en, ru
      static let metricActionsDelete = Rswift.StringResource(key: "metric.actions.delete", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Request settings
      ///
      /// Locales: en, ru
      static let addmetricSectionRequestSettings = Rswift.StringResource(key: "addmetric.section.request-settings", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Save
      ///
      /// Locales: en, ru
      static let commonSave = Rswift.StringResource(key: "common.save", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Select HTTP Header
      ///
      /// Locales: en, ru
      static let httpheadersSelectTitle = Rswift.StringResource(key: "httpheaders.select.title", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Select HTTP-header from list
      ///
      /// Locales: en, ru
      static let httpheadersSelectFromList = Rswift.StringResource(key: "httpheaders.select-from-list", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Select Value
      ///
      /// Locales: en, ru
      static let httpheadersSelectValueTitle = Rswift.StringResource(key: "httpheaders.select.value-title", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Select action for metric «%@»
      ///
      /// Locales: en, ru
      static let metricActionsTitle = Rswift.StringResource(key: "metric.actions.title", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Select check
      ///
      /// Locales: en, ru
      static let addmetricFieldTypeParseRuleTitle = Rswift.StringResource(key: "addmetric.field.type-parse-rule-title", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Select value from list
      ///
      /// Locales: en, ru
      static let httpheadersSelectValuesFromList = Rswift.StringResource(key: "httpheaders.select-values-from-list", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Specify a value that must match the result of processing the response. For example: you want to check if the answer matches the value "100"
      ///
      /// Locales: en, ru
      static let addmetricFieldRuleTypeEqualDescription = Rswift.StringResource(key: "addmetric.field.rule-type-equal-description", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Specify the value that will be contained as a result of processing the response. For example: you want to check if a string contains the word "error"
      ///
      /// Locales: en, ru
      static let addmetricFieldRuleTypeContainsDescription = Rswift.StringResource(key: "addmetric.field.rule-type-contains-description", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: This HTTP-header and value will be send in every request for get metric value.
      ///
      /// Locales: en, ru
      static let httpheadersValueInformation = Rswift.StringResource(key: "httpheaders.value-information", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Title
      ///
      /// Locales: en, ru
      static let addmetricFieldTitle = Rswift.StringResource(key: "addmetric.field.title", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Type metric
      ///
      /// Locales: en, ru
      static let addmetricFieldTypeMetric = Rswift.StringResource(key: "addmetric.field.type-metric", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: URL
      ///
      /// Locales: en, ru
      static let addmetricFieldUrl = Rswift.StringResource(key: "addmetric.field.url", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Value settings
      ///
      /// Locales: en, ru
      static let addmetricSectionValueSettings = Rswift.StringResource(key: "addmetric.section.value-settings", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Value type
      ///
      /// Locales: en, ru
      static let addmetricFieldValueType = Rswift.StringResource(key: "addmetric.field.value-type", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Version: %@
      ///
      /// Locales: en, ru
      static let infoVersion = Rswift.StringResource(key: "info.version", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: You sure?
      ///
      /// Locales: en, ru
      static let metricActionsSure = Rswift.StringResource(key: "metric.actions.sure", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: https://yourapi.com/
      ///
      /// Locales: en, ru
      static let addmetricFieldUrlPlaceholder = Rswift.StringResource(key: "addmetric.field.url-placeholder", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)

      /// en translation: About
      ///
      /// Locales: en, ru
      static func infoTitle(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("info.title", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "info.title"
        }

        return NSLocalizedString("info.title", bundle: bundle, comment: "")
      }

      /// en translation: Add
      ///
      /// Locales: en, ru
      static func httpheadersAddButton(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("httpheaders.add.button", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "httpheaders.add.button"
        }

        return NSLocalizedString("httpheaders.add.button", bundle: bundle, comment: "")
      }

      /// en translation: Add
      ///
      /// Locales: en, ru
      static func metricAdd(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("metric.add", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "metric.add"
        }

        return NSLocalizedString("metric.add", bundle: bundle, comment: "")
      }

      /// en translation: Add Header
      ///
      /// Locales: en, ru
      static func addmetricButtonAddHttpHeader(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("addmetric.button.add-http-header", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "addmetric.button.add-http-header"
        }

        return NSLocalizedString("addmetric.button.add-http-header", bundle: bundle, comment: "")
      }

      /// en translation: Add Header
      ///
      /// Locales: en, ru
      static func httpheadersAddTitle(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("httpheaders.add.title", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "httpheaders.add.title"
        }

        return NSLocalizedString("httpheaders.add.title", bundle: bundle, comment: "")
      }

      /// en translation: Add Metric
      ///
      /// Locales: en, ru
      static func metricAddTitle(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("metric.add.title", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "metric.add.title"
        }

        return NSLocalizedString("metric.add.title", bundle: bundle, comment: "")
      }

      /// en translation: Add metric
      ///
      /// Locales: en, ru
      static func addmetricButtonAdd(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("addmetric.button.add", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "addmetric.button.add"
        }

        return NSLocalizedString("addmetric.button.add", bundle: bundle, comment: "")
      }

      /// en translation: AnyMetrics
      ///
      /// Locales: en, ru
      static func appName(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("appName", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "appName"
        }

        return NSLocalizedString("appName", bundle: bundle, comment: "")
      }

      /// en translation: AnyMetrics is open source project. Developed to solve own problem and published on GitHub.  If want to add metric to gallery send PullRequest to gallery repository.
      ///
      /// Locales: en, ru
      static func infoMessage(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("info.message", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "info.message"
        }

        return NSLocalizedString("info.message", bundle: bundle, comment: "")
      }

      /// en translation: Application code
      ///
      /// Locales: en, ru
      static func infoGithubAppRepo(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("info.github-app-repo", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "info.github-app-repo"
        }

        return NSLocalizedString("info.github-app-repo", bundle: bundle, comment: "")
      }

      /// en translation: Bad
      ///
      /// Locales: en, ru
      static func metricValueBad(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("metric.value.bad", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "metric.value.bad"
        }

        return NSLocalizedString("metric.value.bad", bundle: bundle, comment: "")
      }

      /// en translation: Bitcoin
      ///
      /// Locales: en, ru
      static func addmetricFieldTitlePlaceholder(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("addmetric.field.title-placeholder", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "addmetric.field.title-placeholder"
        }

        return NSLocalizedString("addmetric.field.title-placeholder", bundle: bundle, comment: "")
      }

      /// en translation: Case sensitive
      ///
      /// Locales: en, ru
      static func addmetricFieldCaseSensitive(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("addmetric.field.case-sensitive", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "addmetric.field.case-sensitive"
        }

        return NSLocalizedString("addmetric.field.case-sensitive", bundle: bundle, comment: "")
      }

      /// en translation: Check HTTP Status (20x is success)
      ///
      /// Locales: en, ru
      static func addmetricFieldTypeMetricCheckstatus(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("addmetric.field.type-metric-checkstatus", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "addmetric.field.type-metric-checkstatus"
        }

        return NSLocalizedString("addmetric.field.type-metric-checkstatus", bundle: bundle, comment: "")
      }

      /// en translation: Close
      ///
      /// Locales: en, ru
      static func commonClose(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("common.close", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "common.close"
        }

        return NSLocalizedString("common.close", bundle: bundle, comment: "")
      }

      /// en translation: Compare
      ///
      /// Locales: en, ru
      static func addmetricFieldRuleTypeEqual(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("addmetric.field.rule-type-equal", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "addmetric.field.rule-type-equal"
        }

        return NSLocalizedString("addmetric.field.rule-type-equal", bundle: bundle, comment: "")
      }

      /// en translation: Configure
      ///
      /// Locales: en, ru
      static func addmetricFieldValueConfigure(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("addmetric.field.value-configure", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "addmetric.field.value-configure"
        }

        return NSLocalizedString("addmetric.field.value-configure", bundle: bundle, comment: "")
      }

      /// en translation: Create custom metric
      ///
      /// Locales: en, ru
      static func metricAddCustom(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("metric.add.custom", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "metric.add.custom"
        }

        return NSLocalizedString("metric.add.custom", bundle: bundle, comment: "")
      }

      /// en translation: Currency
      ///
      /// Locales: en, ru
      static func addmetricFieldValueTypeCurrency(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("addmetric.field.value-type-currency", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "addmetric.field.value-type-currency"
        }

        return NSLocalizedString("addmetric.field.value-type-currency", bundle: bundle, comment: "")
      }

      /// en translation: Cut if longer
      ///
      /// Locales: en, ru
      static func addmetricFieldMaxLength(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("addmetric.field.max-length", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "addmetric.field.max-length"
        }

        return NSLocalizedString("addmetric.field.max-length", bundle: bundle, comment: "")
      }

      /// en translation: Delete metric
      ///
      /// Locales: en, ru
      static func metricActionsConfirmDelete(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("metric.actions.confirmDelete", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "metric.actions.confirmDelete"
        }

        return NSLocalizedString("metric.actions.confirmDelete", bundle: bundle, comment: "")
      }

      /// en translation: Edit
      ///
      /// Locales: en, ru
      static func addmetricTitleEdit(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("addmetric.title-edit", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "addmetric.title-edit"
        }

        return NSLocalizedString("addmetric.title-edit", bundle: bundle, comment: "")
      }

      /// en translation: Edit
      ///
      /// Locales: en, ru
      static func metricActionsEdit(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("metric.actions.edit", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "metric.actions.edit"
        }

        return NSLocalizedString("metric.actions.edit", bundle: bundle, comment: "")
      }

      /// en translation: Enter parse HTML rule, see FAQ
      ///
      /// Locales: en, ru
      static func addmetricFieldHtmlParseRulePlaceholder(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("addmetric.field.html-parse-rule-placeholder", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "addmetric.field.html-parse-rule-placeholder"
        }

        return NSLocalizedString("addmetric.field.html-parse-rule-placeholder", bundle: bundle, comment: "")
      }

      /// en translation: Enter parse JSON rule, see FAQ
      ///
      /// Locales: en, ru
      static func addmetricFieldJsonParseRulePlaceholder(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("addmetric.field.json-parse-rule-placeholder", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "addmetric.field.json-parse-rule-placeholder"
        }

        return NSLocalizedString("addmetric.field.json-parse-rule-placeholder", bundle: bundle, comment: "")
      }

      /// en translation: Enter value
      ///
      /// Locales: en, ru
      static func addmetricFieldRuleTypePlaceholder(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("addmetric.field.rule-type-placeholder", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "addmetric.field.rule-type-placeholder"
        }

        return NSLocalizedString("addmetric.field.rule-type-placeholder", bundle: bundle, comment: "")
      }

      /// en translation: FAQ
      ///
      /// Locales: en, ru
      static func commonFaq(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("common.faq", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "common.faq"
        }

        return NSLocalizedString("common.faq", bundle: bundle, comment: "")
      }

      /// en translation: Format settings
      ///
      /// Locales: en, ru
      static func addmetricSectionFormatSettings(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("addmetric.section.format-settings", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "addmetric.section.format-settings"
        }

        return NSLocalizedString("addmetric.section.format-settings", bundle: bundle, comment: "")
      }

      /// en translation: Gallery repository
      ///
      /// Locales: en, ru
      static func infoGithubGalleryRepo(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("info.github-gallery-repo", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "info.github-gallery-repo"
        }

        return NSLocalizedString("info.github-gallery-repo", bundle: bundle, comment: "")
      }

      /// en translation: Good
      ///
      /// Locales: en, ru
      static func metricValueGood(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("metric.value.good", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "metric.value.good"
        }

        return NSLocalizedString("metric.value.good", bundle: bundle, comment: "")
      }

      /// en translation: HTTP Headers
      ///
      /// Locales: en, ru
      static func addmetricSectionHttpHeaders(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("addmetric.section.http-headers", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "addmetric.section.http-headers"
        }

        return NSLocalizedString("addmetric.section.http-headers", bundle: bundle, comment: "")
      }

      /// en translation: HTTP Method
      ///
      /// Locales: en, ru
      static func addmetricFieldHttpMethod(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("addmetric.field.http-method", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "addmetric.field.http-method"
        }

        return NSLocalizedString("addmetric.field.http-method", bundle: bundle, comment: "")
      }

      /// en translation: HTTP-header title
      ///
      /// Locales: en, ru
      static func httpheadersEnterName(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("httpheaders.enter-name", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "httpheaders.enter-name"
        }

        return NSLocalizedString("httpheaders.enter-name", bundle: bundle, comment: "")
      }

      /// en translation: Header Value
      ///
      /// Locales: en, ru
      static func httpheadersEnterValue(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("httpheaders.enter-value", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "httpheaders.enter-value"
        }

        return NSLocalizedString("httpheaders.enter-value", bundle: bundle, comment: "")
      }

      /// en translation: Make request
      ///
      /// Locales: en, ru
      static func addmetricButtonMakeRequest(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("addmetric.button.make-request", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "addmetric.button.make-request"
        }

        return NSLocalizedString("addmetric.button.make-request", bundle: bundle, comment: "")
      }

      /// en translation: Measure
      ///
      /// Locales: en, ru
      static func addmetricFieldParamMeasure(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("addmetric.field.param-measure", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "addmetric.field.param-measure"
        }

        return NSLocalizedString("addmetric.field.param-measure", bundle: bundle, comment: "")
      }

      /// en translation: Must contain
      ///
      /// Locales: en, ru
      static func addmetricFieldRuleTypeContains(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("addmetric.field.rule-type-contains", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "addmetric.field.rule-type-contains"
        }

        return NSLocalizedString("addmetric.field.rule-type-contains", bundle: bundle, comment: "")
      }

      /// en translation: New metric
      ///
      /// Locales: en, ru
      static func addmetricTitleNew(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("addmetric.title-new", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "addmetric.title-new"
        }

        return NSLocalizedString("addmetric.title-new", bundle: bundle, comment: "")
      }

      /// en translation: No
      ///
      /// Locales: en, ru
      static func addmetricFieldRuleTypeNone(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("addmetric.field.rule-type-none", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "addmetric.field.rule-type-none"
        }

        return NSLocalizedString("addmetric.field.rule-type-none", bundle: bundle, comment: "")
      }

      /// en translation: No response
      ///
      /// Locales: en, ru
      static func addmetricTextNoResponse(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("addmetric.text.no-response", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "addmetric.text.no-response"
        }

        return NSLocalizedString("addmetric.text.no-response", bundle: bundle, comment: "")
      }

      /// en translation: Optional
      ///
      /// Locales: en, ru
      static func commonOptional(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("common.optional", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "common.optional"
        }

        return NSLocalizedString("common.optional", bundle: bundle, comment: "")
      }

      /// en translation: Parse HTML
      ///
      /// Locales: en, ru
      static func addmetricFieldTypeMetricWeb(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("addmetric.field.type-metric-web", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "addmetric.field.type-metric-web"
        }

        return NSLocalizedString("addmetric.field.type-metric-web", bundle: bundle, comment: "")
      }

      /// en translation: Parse JSON
      ///
      /// Locales: en, ru
      static func addmetricFieldTypeMetricJson(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("addmetric.field.type-metric-json", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "addmetric.field.type-metric-json"
        }

        return NSLocalizedString("addmetric.field.type-metric-json", bundle: bundle, comment: "")
      }

      /// en translation: Press + and add your first metric
      ///
      /// Locales: en, ru
      static func metricPlaceholder(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("metric.placeholder", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "metric.placeholder"
        }

        return NSLocalizedString("metric.placeholder", bundle: bundle, comment: "")
      }

      /// en translation: Price, USD
      ///
      /// Locales: en, ru
      static func addmetricFieldParamMeasurePlaceholder(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("addmetric.field.param-measure-placeholder", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "addmetric.field.param-measure-placeholder"
        }

        return NSLocalizedString("addmetric.field.param-measure-placeholder", bundle: bundle, comment: "")
      }

      /// en translation: Rate application
      ///
      /// Locales: en, ru
      static func infoRate(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("info.rate", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "info.rate"
        }

        return NSLocalizedString("info.rate", bundle: bundle, comment: "")
      }

      /// en translation: Raw
      ///
      /// Locales: en, ru
      static func addmetricFieldValueTypeNone(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("addmetric.field.value-type-none", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "addmetric.field.value-type-none"
        }

        return NSLocalizedString("addmetric.field.value-type-none", bundle: bundle, comment: "")
      }

      /// en translation: Refresh
      ///
      /// Locales: en, ru
      static func metricActionsUpdateValue(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("metric.actions.update-value", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "metric.actions.update-value"
        }

        return NSLocalizedString("metric.actions.update-value", bundle: bundle, comment: "")
      }

      /// en translation: Remove
      ///
      /// Locales: en, ru
      static func metricActionsDelete(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("metric.actions.delete", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "metric.actions.delete"
        }

        return NSLocalizedString("metric.actions.delete", bundle: bundle, comment: "")
      }

      /// en translation: Request settings
      ///
      /// Locales: en, ru
      static func addmetricSectionRequestSettings(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("addmetric.section.request-settings", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "addmetric.section.request-settings"
        }

        return NSLocalizedString("addmetric.section.request-settings", bundle: bundle, comment: "")
      }

      /// en translation: Save
      ///
      /// Locales: en, ru
      static func commonSave(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("common.save", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "common.save"
        }

        return NSLocalizedString("common.save", bundle: bundle, comment: "")
      }

      /// en translation: Select HTTP Header
      ///
      /// Locales: en, ru
      static func httpheadersSelectTitle(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("httpheaders.select.title", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "httpheaders.select.title"
        }

        return NSLocalizedString("httpheaders.select.title", bundle: bundle, comment: "")
      }

      /// en translation: Select HTTP-header from list
      ///
      /// Locales: en, ru
      static func httpheadersSelectFromList(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("httpheaders.select-from-list", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "httpheaders.select-from-list"
        }

        return NSLocalizedString("httpheaders.select-from-list", bundle: bundle, comment: "")
      }

      /// en translation: Select Value
      ///
      /// Locales: en, ru
      static func httpheadersSelectValueTitle(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("httpheaders.select.value-title", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "httpheaders.select.value-title"
        }

        return NSLocalizedString("httpheaders.select.value-title", bundle: bundle, comment: "")
      }

      /// en translation: Select action for metric «%@»
      ///
      /// Locales: en, ru
      static func metricActionsTitle(_ value1: String, preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          let format = NSLocalizedString("metric.actions.title", bundle: hostingBundle, comment: "")
          return String(format: format, locale: applicationLocale, value1)
        }

        guard let (locale, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "metric.actions.title"
        }

        let format = NSLocalizedString("metric.actions.title", bundle: bundle, comment: "")
        return String(format: format, locale: locale, value1)
      }

      /// en translation: Select check
      ///
      /// Locales: en, ru
      static func addmetricFieldTypeParseRuleTitle(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("addmetric.field.type-parse-rule-title", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "addmetric.field.type-parse-rule-title"
        }

        return NSLocalizedString("addmetric.field.type-parse-rule-title", bundle: bundle, comment: "")
      }

      /// en translation: Select value from list
      ///
      /// Locales: en, ru
      static func httpheadersSelectValuesFromList(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("httpheaders.select-values-from-list", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "httpheaders.select-values-from-list"
        }

        return NSLocalizedString("httpheaders.select-values-from-list", bundle: bundle, comment: "")
      }

      /// en translation: Specify a value that must match the result of processing the response. For example: you want to check if the answer matches the value "100"
      ///
      /// Locales: en, ru
      static func addmetricFieldRuleTypeEqualDescription(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("addmetric.field.rule-type-equal-description", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "addmetric.field.rule-type-equal-description"
        }

        return NSLocalizedString("addmetric.field.rule-type-equal-description", bundle: bundle, comment: "")
      }

      /// en translation: Specify the value that will be contained as a result of processing the response. For example: you want to check if a string contains the word "error"
      ///
      /// Locales: en, ru
      static func addmetricFieldRuleTypeContainsDescription(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("addmetric.field.rule-type-contains-description", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "addmetric.field.rule-type-contains-description"
        }

        return NSLocalizedString("addmetric.field.rule-type-contains-description", bundle: bundle, comment: "")
      }

      /// en translation: This HTTP-header and value will be send in every request for get metric value.
      ///
      /// Locales: en, ru
      static func httpheadersValueInformation(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("httpheaders.value-information", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "httpheaders.value-information"
        }

        return NSLocalizedString("httpheaders.value-information", bundle: bundle, comment: "")
      }

      /// en translation: Title
      ///
      /// Locales: en, ru
      static func addmetricFieldTitle(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("addmetric.field.title", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "addmetric.field.title"
        }

        return NSLocalizedString("addmetric.field.title", bundle: bundle, comment: "")
      }

      /// en translation: Type metric
      ///
      /// Locales: en, ru
      static func addmetricFieldTypeMetric(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("addmetric.field.type-metric", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "addmetric.field.type-metric"
        }

        return NSLocalizedString("addmetric.field.type-metric", bundle: bundle, comment: "")
      }

      /// en translation: URL
      ///
      /// Locales: en, ru
      static func addmetricFieldUrl(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("addmetric.field.url", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "addmetric.field.url"
        }

        return NSLocalizedString("addmetric.field.url", bundle: bundle, comment: "")
      }

      /// en translation: Value settings
      ///
      /// Locales: en, ru
      static func addmetricSectionValueSettings(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("addmetric.section.value-settings", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "addmetric.section.value-settings"
        }

        return NSLocalizedString("addmetric.section.value-settings", bundle: bundle, comment: "")
      }

      /// en translation: Value type
      ///
      /// Locales: en, ru
      static func addmetricFieldValueType(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("addmetric.field.value-type", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "addmetric.field.value-type"
        }

        return NSLocalizedString("addmetric.field.value-type", bundle: bundle, comment: "")
      }

      /// en translation: Version: %@
      ///
      /// Locales: en, ru
      static func infoVersion(_ value1: String, preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          let format = NSLocalizedString("info.version", bundle: hostingBundle, comment: "")
          return String(format: format, locale: applicationLocale, value1)
        }

        guard let (locale, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "info.version"
        }

        let format = NSLocalizedString("info.version", bundle: bundle, comment: "")
        return String(format: format, locale: locale, value1)
      }

      /// en translation: You sure?
      ///
      /// Locales: en, ru
      static func metricActionsSure(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("metric.actions.sure", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "metric.actions.sure"
        }

        return NSLocalizedString("metric.actions.sure", bundle: bundle, comment: "")
      }

      /// en translation: https://yourapi.com/
      ///
      /// Locales: en, ru
      static func addmetricFieldUrlPlaceholder(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("addmetric.field.url-placeholder", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "addmetric.field.url-placeholder"
        }

        return NSLocalizedString("addmetric.field.url-placeholder", bundle: bundle, comment: "")
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }

  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      // There are no resources to validate
    }

    fileprivate init() {}
  }

  fileprivate class Class {}

  fileprivate init() {}
}

struct _R {
  fileprivate init() {}
}
